### ISSUE TITLE
meteor-counter-cache incompatible with Meteor 1.1?

### ISSUE THREAD

**Issue by hazio** [versolearning/meteor-counter-cache#1]
Hello!

First of all I want to thank you for creating & sharing this really useful package with Meteor community.

After upgrading to Meteor version 1.1 I got this exception:

```
W20150401-13:07:15.059(3)? (STDERR) The package mrt:collection-hooks at 0.6.7 is incompatible with Meteor 0.9.0 or later. 
W20150401-13:07:15.060(3)? (STDERR) If a new, compatible version of this package exists, running 'meteor update' should cause you to update. 
W20150401-13:07:15.715(3)? (STDERR) 
W20150401-13:07:15.715(3)? (STDERR) /home/hakki/.meteor/packages/meteor-tool/.1.1.1.11wce6u++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150401-13:07:15.715(3)? (STDERR)                         throw(ex);
W20150401-13:07:15.715(3)? (STDERR)                               ^
W20150401-13:07:15.721(3)? (STDERR) TypeError: Cannot call method 'insert' of undefined
W20150401-13:07:15.721(3)? (STDERR)     at [object Object].Mongo.Collection.maintainCountOf (packages/dburles:counter-cache/counter-cache.js:54:1)
W20150401-13:07:15.721(3)? (STDERR)     at app/server/startup/init/counter.js:3:10
```

Any ideas what is broken?

EDIT: I got it working by replacing mrt:collection-hooks@0.6.3 with matb33:collection-hooks@0.7.11

**Comment by hazio** [comment]
Forked version: https://github.com/hazio/meteor-counter-cache

**Comment by dburles** [comment]
Hey @hazio feel free to send us a PR.
